# Generated by Django 2.2.6 on 2019-10-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxiuser',
            name='user_type',
            field=models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger')], max_length=24),
        ),
    ]
