# Generated by Django 2.2.6 on 2019-10-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_auto_20191013_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='cash_type',
            new_name='payment_type',
        ),
    ]
