# Generated by Django 2.2.6 on 2019-10-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_auto_20191014_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
